seo:
  keys: [ 'оценка', 'оценка для ипотеки', 'акредитация в банке', 'бесплатная консультация' ]
  title: Услуги
block1: |-
  # Services
  ## Common
  Text is ok but you need to do some minor corrects

