phones:
  - +7(963)689-55-99
  - +7(495)796-25-50
  - +7(917)593-00-24
email: val@inbico.com
vkUrl: /vkUrl
ytUrl: /ytUrl
telegramChanel: somechanelId
address: 115409, Москва, Каширское ш., дом 66, корп. 2, оф.33
userActionEndpoint: /userActionEndpoint
