backend:
  name: test-repo
  branch: master
media_folder: public/images
public_folder: images

collections:
  - name: "pages"
    label: "Основные страницы сайта"
    files:
      - label: "Prices"
        name: "Цены"
        file: "content/prices.md"
        fields:
          - { label: "Текстовый блок", name: "block1", widget: "markdown" }
          - label: Прайслист
            name: priceList
            widget: list
            fields:
              - label: Название группы
                name: groupName
                widget: string
              - label: Объекты
                name: items,
                widget: list
                fields:
                  - { label: "Объект оценки", name: object, widget: string }
                  - { label: "Примечание", name: description, widget: string }
                  - { label: "Сроки исполнения, дней", name: duration, widget: string }
                  - { label: "Стоимость услуг (заключение), руб.", name: price1, widget: string }
                  - { label: "Стоимость услуг (отчет), руб.", name: price2, widget: string }
