import type { NextPage } from 'next'
import Head from 'next/head'
import { Partners } from '../components/Partners';
import { Banks } from '../components/Banks';
import { Feedback } from '../components/Feedback';
import { Showcase } from '../components/Showcase';
import { ArticlesPreview } from '../components/ArticlesPreview';
import { BasePageTemplate } from '../components/templates/BasePageTemplate';

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
                <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
            </Head>

            <BasePageTemplate>
                <Showcase/>

                <section className="h-full flex flex-col items-center justify-center">
                    <Feedback/>
                    <ArticlesPreview header="УСЛУГИ" bgGray/>
                    <Banks/>
                    <ArticlesPreview header="ИНФОРМАЦИЯ" bgGray/>
                    <Partners/>
                </section>
            </BasePageTemplate>
        </>
    )
}

export default Home
